[homepage] [s] Small changes on new homepage
life-itself/community pull request #456
Opened 2023-04-17 21:00 UTC by nathenf

It took me a lot of time to get set up using VS Code etc and haven't made a huge impact. 

- Lists 3 key articles
- Lists our top 3 initiatives

2023-04-18 10:51 UTC, rufuspollock commented
👏 @nathenf  it is working https://6a481c30.lifeitself-org.pages.dev/home-new - well done.

2023-04-18 10:52 UTC, rufuspollock requested changes
All looks good except for accidentally added page. I'd suggest closing this PR and just pushing directly to main with the pages to home-new (no need for a PR again).

2023-04-18 10:52 UTC, rufuspollock commented on content/residencies-and-courses/index
@nathenf i think you add this page by mistake as we have programs ...

2023-04-19 06:24 UTC, rufuspollock commented on content/residencies-and-courses/index
Or we can just merge ... and you remove later 😆

2023-04-20 23:26 UTC, nathenf commented on content/residencies-and-courses/index
I'll merge and remove. I'm not sure how this happened...

2023-04-20 23:26 UTC, merged