Community calendar added to community page
life-itself/community pull request #866
Opened 2023-10-16 07:08 UTC by nathenf

- Added a view of the calendar to community page
- Included a link to subscribe to the community calendar

2023-10-16 07:18 UTC, nathenf commented
Hey @olayway I've tried to integrate google calendar into this page and it builds but when I check the preview I get: 

_Application error: a client-side exception has occurred (see the browser console for more information)._ 

I can't figure out why or what this means. Could you assist? 🙏

2023-10-19 08:05 UTC, rufuspollock requested changes
I think i've found a fix for you!

2023-10-19 08:05 UTC, rufuspollock commented on content/community.md
> +<iframe src="https://calendar.google.com/calendar/embed?height=600&wkst=2&bgcolor=%23f0ca5e&ctz=Africa%2FCeuta&hl=en_GB&showPrint=0&showTitle=0&showCalendars=0&src=Y19kMDY0NjNiYzhiZmU4YWVlNjI1OTkyMTB
I suspect this is the source of the problem in that you have to use React style stuff when doing html  ...

Specifically style is tricky and i think you need to do it as a property i.e. like this

```
style={{border-width: "0"}}
```

```
<iframe src="https://calendar.google.com/calendar/embed?height=600&wkst=2&bgcolor=%23f0ca5e&ctz=Africa%2FCeuta&hl=en_GB&showPrint=0&showTitle=0&showCalendars=0&src=Y19kMDY0NjNiYzhiZmU4YWVlNjI1OTkyMTBmNDI3YzMxNzY0YjhkMjFlYmRhZWY5MDhlNTBhMGYyZWE0YTM1ODVlQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&color=%23E4C441" style={{border-width: "0"}} width="800" height="600" frameborder="0" scrolling="no"
```

For background see https://github.com/datopian/flowershow/issues/508#issuecomment-1559970929

2023-10-19 08:05 UTC, rufuspollock commented on content/community.md
> +👉 [Subscribe to the community calendar](https://calendar.google.com/calendar/u/0?cid=Y19kMDY0NjNiYzhiZmU4YWVlNjI1OTkyMTBmNDI3YzMxNzY0YjhkMjFlYmRhZWY5MDhlNTBhMGYyZWE0YTM1ODVlQGdyb3VwLmNhbGVuZGFyLmdvb2
I'd recommend a blank line after this before the html ...

2023-10-19 20:28 UTC, rufuspollock commented
FIXED ... finally. https://embed-calendar-community-cal.lifeitself-org.pages.dev/community

![image](https://github.com/life-itself/community/assets/180658/2e655745-b513-4f0c-a65b-c7943d3008f6)

2023-10-19 20:30 UTC, merged